In [10]:
import numpy as np 

In [13]:
x = np.random.random()
print(x)

0.5732567092457078


In [16]:
y = np.random.random(5)
print(y)

[0.02078928 0.56657676 0.82050083 0.76460261 0.32749748]


In [19]:
array_random = np.random.random((5, 5))
print(array_random)

[[0.59528604 0.34441256 0.84190929 0.58444021 0.86106235]
 [0.60571364 0.17438558 0.3990117  0.97220018 0.58605741]
 [0.97275937 0.98237671 0.97614151 0.40084486 0.7098006 ]
 [0.77817496 0.69781503 0.66862351 0.34907682 0.19004547]
 [0.66621263 0.04254115 0.62294299 0.79931446 0.43041933]]


In [20]:
x1 = np.random.rand(3)
print(x1)

[0.59758621 0.01139068 0.85515612]


In [22]:
x2 = np.random.rand(3, 4)
print(x2)

[[0.1138555  0.3256641  0.44474545 0.73676854]
 [0.89109925 0.65228945 0.94847248 0.27154953]
 [0.05509153 0.32626259 0.25381824 0.41299014]]


In [26]:
x3 = np.random.randint(-20, 20)
print(x3)

-13


In [29]:
x4 = np.random.randint(-100, 100, size=(5,5))
print(x4)

[[-33 -87 -80  -7  16]
 [-26  74  99  -4  54]
 [-26  27 -90 -23  51]
 [-31  -8 -51  62  86]
 [-97 -53 -68 -75  66]]


In [33]:
x5 = np.random.choice(["a", "b", "c", "d", "e"], p = [0.1, 0.5, 0.3, 0, 0.1], size = (6, 5))
print(x5)

[['b' 'c' 'c' 'b' 'e']
 ['b' 'b' 'b' 'c' 'b']
 ['b' 'b' 'c' 'a' 'b']
 ['c' 'b' 'b' 'a' 'e']
 ['e' 'b' 'b' 'b' 'b']
 ['c' 'c' 'a' 'b' 'a']]
