In [6]:
import numpy as np

In [9]:
x = np.array([[2, 4], [5.7, 5.1]])
y = np.array([[1, 4], [8, 10]])
print(x)
print("+-+-+-+-+-")
print(y)
print("+-+-+-+-+-")
print(np.multiply(x,y)) # --> *
print("+-+-+-+-+-")
print(np.matmul(x,y))

[[2.  4. ]
 [5.7 5.1]]
+-+-+-+-+-
[[ 1  4]
 [ 8 10]]
+-+-+-+-+-
[[ 2.  16. ]
 [45.6 51. ]]
+-+-+-+-+-
[[34.  48. ]
 [46.5 73.8]]


In [11]:
d = np.array([[25, 36], [4, 28]])
print(np.sqrt(d))

[[5.         6.        ]
 [2.         5.29150262]]


In [12]:
o = np.array([[-32, 3], [-4, -2]])
print(np.fabs(o))

[[32.  3.]
 [ 4.  2.]]


In [14]:
t = np.zeros((10, 6))
print(t)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [16]:
t1 = np.ones((10, 6))
print(t1)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [19]:
t2 = np.full((10, 6), 9)
print(t2)

[[9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]]


In [21]:
t3 = np.eye(9)
print(t3)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
