In [2]:
import numpy as np 

In [2]:
data = np.array([1, 2, 3, 4])
data2 = np.array([[1, 2], [3, 4]])
data3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(data)
print("=========")
print(data2)
print("=========")
print(data3)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
x = np.array([[1,1], [2,2], [3,3]])
y = np.array([[5,4], [4,7], [5,5]])
print(x+y)
print("=========")
print(x-y)
print("=========")
print(x*y)
print("=========")
print(x/y)
print("=========")
print(x**y)
print("=========")

[[6 5]
 [6 9]
 [8 8]]
[[-4 -3]
 [-2 -5]
 [-2 -2]]
[[ 5  4]
 [ 8 14]
 [15 15]]
[[0.2        0.25      ]
 [0.5        0.28571429]
 [0.6        0.6       ]]
[[  1   1]
 [ 16 128]
 [243 243]]


In [7]:
t = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(t)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
type(t)

numpy.ndarray

In [5]:
t.ndim

2

In [6]:
t.shape

(3, 4)

In [8]:
t.size

12

In [9]:
data3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [10]:
data3.ndim

3

In [12]:
data3.shape

(2, 2, 3)